### ISSUE TITLE
bug: Coinbase Wallet account stays logged in after refresh

### ISSUE THREAD

**Issue by fred-dinari** [wagmi-dev/references#478] opened 2023-08-15 17:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.12.12

### Current Behavior

Steps to reproduce:

1. log into wagmi using a coinbase wallet
2. log out using useDisconnect.disconnect
3. refresh the page

The account is still logged in

### Expected Behavior

upon refresh, no accounts should be logged in

### Steps To Reproduce

1. log into wagmi using a coinbase wallet
2. log out using useDisconnect.disconnect
3. refresh the page

```
import {configureChains, createClient} from 'wagmi';
import * as wagmiChains from 'wagmi/chains';
import {jsonRpcProvider} from 'wagmi/providers/jsonRpc';

const url = new URL({web3JsonRpcUrl});
url.protocol = 'wss';
const webSocketUrl = url.toString();

const {chain, provider} = configureChains(
        [wagmiChains.sepolia],
        [
          jsonRpcProvider({
            rpc: (_chain) => ({
              http: {web3JsonRpcUrl},
              webSocket: webSocketUrl,
            }),
          }),
        ]
      ),

const connector = new CoinbaseWalletConnector({
        chains,
        options: {
          appName: 'Test App',
          headlessMode: true,
        },
});

const client = createClient({
      autoConnect: true,
      provider: provider,
      connectors: [connector],
    });
    
    
<WagmiConfig client={wagmiClient}>< App /></WagmiConfig>
```

Logging in:
```
import {useConnect} from 'wagmi';


const {connect} = useConnect();
const login = connect
```

log out:
```
import {useDisconnect} from 'wagmi';

const {disconnect} = useDisconnect();
const logout = disconnect;
```

**Comment by glitch-txs** [comment] 2023-08-15 21:38
Just tested and works fine on my end. Have you tried cleaning up localStorage/cache?

**Comment by fred-dinari** [comment] 2023-08-15 23:05
When I was testing this locally, I cleared the cache/localStorage but the issue still popped up

**Comment by tmm** [comment] 2023-08-31 20:24
I'm not able to reproduce with Coinbase Wallet browser extension version `3.33.1`. What version are you using? Closing until we figure out a way to reproduce.

**Closed by tmm** 2023-08-31 20:24 UTC
